// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using projectSales.Server.Infrastructure.Persistence;

#nullable disable

namespace projectSales.Server.Migrations
{
    [DbContext(typeof(SalesystemDbContext))]
    [Migration("20251103220943_InitialModel")]
    partial class InitialModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("dbo")
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("projectSales.Server.Domain.Entities.AccessTokenRevocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("expiresAt");

                    b.Property<string>("Jti")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("char(36)")
                        .HasColumnName("jti")
                        .IsFixedLength();

                    b.Property<string>("Reason")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("reason");

                    b.Property<DateTime>("RevokedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("revokedAt")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int?>("SessionId")
                        .HasColumnType("int")
                        .HasColumnName("sessionId");

                    b.HasKey("Id")
                        .HasName("PK_AccessTokenRevocations");

                    b.HasIndex("Jti")
                        .IsUnique()
                        .HasDatabaseName("UX_AccessRevocations_Jti");

                    b.HasIndex("SessionId");

                    b.ToTable("AccessTokenRevocations", "dbo");
                });

            modelBuilder.Entity("projectSales.Server.Domain.Entities.BusinessInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ciudad")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ciudad");

                    b.Property<string>("ContactoEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("contactoEmail");

                    b.Property<string>("ContactoNombre")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("contactoNombre");

                    b.Property<string>("ContactoTelefono")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("contactoTelefono");

                    b.Property<string>("CreadoPor")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("creadoPor");

                    b.Property<string>("Direccion")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("direccion");

                    b.Property<string>("EmpresaNombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("empresaNombre");

                    b.Property<string>("Facebook")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("facebook");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("fechaCreacion")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("fechaModificacion");

                    b.Property<string>("Instagram")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("instagram");

                    b.Property<bool>("IsPrimary")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("isPrimary");

                    b.Property<string>("ModificadoPor")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("modificadoPor");

                    b.Property<string>("Nit")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("nit");

                    b.Property<string>("Pais")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("pais");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("rowVersion");

                    b.Property<string>("Tiktok")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("tiktok");

                    b.Property<string>("Web")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("web");

                    b.HasKey("Id")
                        .HasName("PK_BusinessInfo");

                    b.HasIndex("IsPrimary")
                        .IsUnique()
                        .HasDatabaseName("UX_BusinessInfo_Primary")
                        .HasFilter("[isPrimary] = 1");

                    b.ToTable("BusinessInfo", "dbo");
                });

            modelBuilder.Entity("projectSales.Server.Domain.Entities.CategoriaMaterial", b =>
                {
                    b.Property<int>("CategoriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CategoriaId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoriaId"));

                    b.Property<int?>("CreadoPor")
                        .HasColumnType("int")
                        .HasColumnName("CreadoPor");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Descripcion");

                    b.Property<bool>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("Estado");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(7)")
                        .HasColumnName("FechaCreacion")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2(7)")
                        .HasColumnName("FechaModificacion");

                    b.Property<int?>("ModificadoPor")
                        .HasColumnType("int")
                        .HasColumnName("ModificadoPor");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Nombre");

                    b.HasKey("CategoriaId")
                        .HasName("PK_CategoriasMateriales");

                    b.HasIndex("Nombre")
                        .IsUnique()
                        .HasDatabaseName("UX_CategoriasMateriales_Nombre");

                    b.ToTable("CategoriasMateriales", "dbo");
                });

            modelBuilder.Entity("projectSales.Server.Domain.Entities.Contacto", b =>
                {
                    b.Property<int>("ContactoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ContactoId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ContactoId"));

                    b.Property<string>("Correo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Correo");

                    b.Property<int?>("CreadoPor")
                        .HasColumnType("int")
                        .HasColumnName("CreadoPor");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Descripcion");

                    b.Property<bool>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("Estado");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(7)")
                        .HasColumnName("FechaCreacion")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2(7)")
                        .HasColumnName("FechaModificacion");

                    b.Property<int?>("ModificadoPor")
                        .HasColumnType("int")
                        .HasColumnName("ModificadoPor");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Nombre");

                    b.Property<string>("ProveedorCifId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ProveedorCifId");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Telefono");

                    b.HasKey("ContactoId")
                        .HasName("PK_Contactos");

                    b.HasIndex("ProveedorCifId")
                        .HasDatabaseName("IX_Contactos_Proveedor");

                    b.ToTable("Contactos", "dbo");
                });

            modelBuilder.Entity("projectSales.Server.Domain.Entities.Marca", b =>
                {
                    b.Property<int>("MarcaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MarcaId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MarcaId"));

                    b.Property<int?>("CreadoPor")
                        .HasColumnType("int")
                        .HasColumnName("CreadoPor");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Descripcion");

                    b.Property<bool>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("Estado");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(7)")
                        .HasColumnName("FechaCreacion")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2(7)")
                        .HasColumnName("FechaModificacion");

                    b.Property<int?>("ModificadoPor")
                        .HasColumnType("int")
                        .HasColumnName("ModificadoPor");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Nombre");

                    b.HasKey("MarcaId")
                        .HasName("PK_Marcas");

                    b.HasIndex("Nombre")
                        .IsUnique()
                        .HasDatabaseName("UX_Marcas_Nombre");

                    b.ToTable("Marcas", "dbo");
                });

            modelBuilder.Entity("projectSales.Server.Domain.Entities.Material", b =>
                {
                    b.Property<int>("MaterialId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaterialId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaterialId"));

                    b.Property<int?>("CategoriaId")
                        .HasColumnType("int")
                        .HasColumnName("CategoriaId");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Codigo");

                    b.Property<int?>("CreadoPor")
                        .HasColumnType("int")
                        .HasColumnName("CreadoPor");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("Descripcion");

                    b.Property<bool>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("Estado");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(7)")
                        .HasColumnName("FechaCreacion")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2(7)")
                        .HasColumnName("FechaModificacion");

                    b.Property<int?>("ModificadoPor")
                        .HasColumnType("int")
                        .HasColumnName("ModificadoPor");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Nombre");

                    b.Property<string>("Sku")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("SKU");

                    b.Property<string>("UnidadMedida")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("UnidadMedida");

                    b.HasKey("MaterialId")
                        .HasName("PK_Materiales");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("Codigo")
                        .IsUnique()
                        .HasDatabaseName("UX_Materiales_Codigo");

                    b.HasIndex("Sku")
                        .IsUnique()
                        .HasDatabaseName("UX_Materiales_SKU")
                        .HasFilter("[SKU] IS NOT NULL");

                    b.ToTable("Materiales", "dbo");
                });

            modelBuilder.Entity("projectSales.Server.Domain.Entities.Module", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreadoPor")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("creadoPor");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("fechaCreacion")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("fechaModificacion");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("isActive");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("key");

                    b.Property<string>("ModificadoPor")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("modificadoPor");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("name");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("rowVersion");

                    b.HasKey("Id")
                        .HasName("PK_Modules");

                    b.HasIndex("Key")
                        .IsUnique()
                        .HasDatabaseName("UX_Modules_key");

                    b.ToTable("Modules", "dbo");
                });

            modelBuilder.Entity("projectSales.Server.Domain.Entities.ModuleAction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreadoPor")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("creadoPor");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("fechaCreacion")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("fechaModificacion");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("isActive");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("key");

                    b.Property<string>("ModificadoPor")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("modificadoPor");

                    b.Property<int>("ModuleId")
                        .HasColumnType("int")
                        .HasColumnName("moduleId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("name");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("rowVersion");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("sortOrder");

                    b.HasKey("Id")
                        .HasName("PK_Actions");

                    b.HasIndex("ModuleId", "Key")
                        .IsUnique()
                        .HasDatabaseName("UX_Actions_Module_Key");

                    b.HasIndex("ModuleId", "SortOrder")
                        .IsUnique()
                        .HasDatabaseName("UX_Actions_Module_Sort");

                    b.ToTable("Actions", "dbo");
                });

            modelBuilder.Entity("projectSales.Server.Domain.Entities.PrecioTarifa", b =>
                {
                    b.Property<int>("MaterialId")
                        .HasColumnType("int")
                        .HasColumnName("MaterialId");

                    b.Property<string>("ProveedorCifId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ProveedorCifId");

                    b.Property<int>("MarcaId")
                        .HasColumnType("int")
                        .HasColumnName("MarcaId");

                    b.Property<int?>("CreadoPor")
                        .HasColumnType("int")
                        .HasColumnName("CreadoPor");

                    b.Property<bool>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("Estado");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(7)")
                        .HasColumnName("FechaCreacion")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2(7)")
                        .HasColumnName("FechaModificacion");

                    b.Property<int?>("ModificadoPor")
                        .HasColumnType("int")
                        .HasColumnName("ModificadoPor");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Precio");

                    b.HasKey("MaterialId", "ProveedorCifId", "MarcaId")
                        .HasName("PK_PreciosTarifas");

                    b.HasIndex("MarcaId")
                        .HasDatabaseName("IX_PreciosTarifas_Marca");

                    b.HasIndex("ProveedorCifId")
                        .HasDatabaseName("IX_PreciosTarifas_Prov");

                    b.ToTable("PreciosTarifas", "dbo", t =>
                        {
                            t.HasCheckConstraint("CK_PreciosTarifas_Precio", "[Precio] >= 0");
                        });
                });

            modelBuilder.Entity("projectSales.Server.Domain.Entities.Proveedor", b =>
                {
                    b.Property<string>("ProveedorCifId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ProveedorCifId");

                    b.Property<int?>("CreadoPor")
                        .HasColumnType("int")
                        .HasColumnName("CreadoPor");

                    b.Property<string>("DomicilioSocial")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("DomicilioSocial");

                    b.Property<bool>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("Estado");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(7)")
                        .HasColumnName("FechaCreacion")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2(7)")
                        .HasColumnName("FechaModificacion");

                    b.Property<int?>("ModificadoPor")
                        .HasColumnType("int")
                        .HasColumnName("ModificadoPor");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Nombre");

                    b.HasKey("ProveedorCifId")
                        .HasName("PK_Proveedores");

                    b.HasIndex("Nombre")
                        .IsUnique()
                        .HasDatabaseName("UX_Proveedores_Nombre");

                    b.ToTable("Proveedores", "dbo");
                });

            modelBuilder.Entity("projectSales.Server.Domain.Entities.ProveedorMarca", b =>
                {
                    b.Property<string>("ProveedorCifId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ProveedorCifId");

                    b.Property<int>("MarcaId")
                        .HasColumnType("int")
                        .HasColumnName("MarcaId");

                    b.Property<int?>("CreadoPor")
                        .HasColumnType("int")
                        .HasColumnName("CreadoPor");

                    b.Property<bool>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("Estado");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(7)")
                        .HasColumnName("FechaCreacion")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2(7)")
                        .HasColumnName("FechaModificacion");

                    b.Property<int?>("ModificadoPor")
                        .HasColumnType("int")
                        .HasColumnName("ModificadoPor");

                    b.HasKey("ProveedorCifId", "MarcaId")
                        .HasName("PK_ProveedoresMarcas");

                    b.HasIndex("MarcaId");

                    b.ToTable("ProveedoresMarcas", "dbo");
                });

            modelBuilder.Entity("projectSales.Server.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("createdAt")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("expiresAt");

                    b.Property<int?>("ReplacedByTokenId")
                        .HasColumnType("int")
                        .HasColumnName("replacedByTokenId");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("revokedAt");

                    b.Property<int?>("RotatedFromTokenId")
                        .HasColumnType("int")
                        .HasColumnName("rotatedFromTokenId");

                    b.Property<int>("SessionId")
                        .HasColumnType("int")
                        .HasColumnName("sessionId");

                    b.Property<byte[]>("TokenHash")
                        .IsRequired()
                        .HasColumnType("varbinary(32)")
                        .HasColumnName("tokenHash");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("userId");

                    b.HasKey("Id")
                        .HasName("PK_RefreshTokens");

                    b.HasIndex("ReplacedByTokenId");

                    b.HasIndex("RotatedFromTokenId");

                    b.HasIndex("SessionId")
                        .HasDatabaseName("IX_RefreshTokens_Session");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("UX_RefreshTokens_Hash");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_RefreshTokens_User");

                    b.ToTable("RefreshTokens", "dbo");
                });

            modelBuilder.Entity("projectSales.Server.Domain.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<string>("CreadoPor")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("creadoPor");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("descripcion");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("fechaCreacion")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("fechaModificacion");

                    b.Property<string>("ModificadoPor")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("modificadoPor");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nombre");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("rowVersion");

                    b.HasKey("Id")
                        .HasName("PK_Roles");

                    b.HasIndex("Nombre")
                        .IsUnique()
                        .HasDatabaseName("UX_Roles_nombre");

                    b.ToTable("Roles", "dbo");
                });

            modelBuilder.Entity("projectSales.Server.Domain.Entities.RolePermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ActionId")
                        .HasColumnType("int")
                        .HasColumnName("actionId");

                    b.Property<bool>("Allowed")
                        .HasColumnType("bit")
                        .HasColumnName("allowed");

                    b.Property<string>("CreadoPor")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("creadoPor");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("fechaCreacion")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("fechaModificacion");

                    b.Property<string>("ModificadoPor")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("modificadoPor");

                    b.Property<int>("ModuleId")
                        .HasColumnType("int")
                        .HasColumnName("moduleId");

                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("roleId");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("rowVersion");

                    b.HasKey("Id")
                        .HasName("PK_RolePermissions");

                    b.HasIndex("ActionId");

                    b.HasIndex("ModuleId");

                    b.HasIndex("RoleId", "ModuleId", "ActionId")
                        .IsUnique()
                        .HasDatabaseName("UX_RolePerms_UQ");

                    b.ToTable("RolePermissions", "dbo");
                });

            modelBuilder.Entity("projectSales.Server.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<string>("CreadoPor")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("creadoPor");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("email");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("fechaCreacion")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("fechaModificacion");

                    b.Property<string>("ModificadoPor")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("modificadoPor");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("passwordHash");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("rowVersion");

                    b.Property<DateTime?>("UltimoLoginUtc")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("ultimoLoginUtc");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("PK_Users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("UX_Users_email");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("UX_Users_username");

                    b.ToTable("Users", "dbo");
                });

            modelBuilder.Entity("projectSales.Server.Domain.Entities.UserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("userId");

                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("roleId");

                    b.Property<string>("CreadoPor")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("creadoPor");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("fechaCreacion")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("fechaModificacion");

                    b.Property<string>("ModificadoPor")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("modificadoPor");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("rowVersion");

                    b.HasKey("UserId", "RoleId")
                        .HasName("PK_UserRoles");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", "dbo");
                });

            modelBuilder.Entity("projectSales.Server.Domain.Entities.UserSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("createdAt")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("DeviceName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("deviceName");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("expiresAt");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ipAddress");

                    b.Property<DateTime?>("LastSeenAt")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("lastSeenAt");

                    b.Property<string>("Location")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("location");

                    b.Property<string>("RevokeReason")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("revokeReason");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("revokedAt");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("userAgent");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("userId");

                    b.HasKey("Id")
                        .HasName("PK_UserSessions");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_UserSessions_Active")
                        .HasFilter("[revokedAt] IS NULL");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("UserId"), new[] { "CreatedAt", "LastSeenAt" });

                    b.ToTable("UserSessions", "dbo");
                });

            modelBuilder.Entity("projectSales.Server.Domain.Entities.AccessTokenRevocation", b =>
                {
                    b.HasOne("projectSales.Server.Domain.Entities.UserSession", "Session")
                        .WithMany("AccessTokenRevocations")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_AccessRevocations_Session");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("projectSales.Server.Domain.Entities.Contacto", b =>
                {
                    b.HasOne("projectSales.Server.Domain.Entities.Proveedor", "Proveedor")
                        .WithMany("Contactos")
                        .HasForeignKey("ProveedorCifId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Contactos_Proveedor");

                    b.Navigation("Proveedor");
                });

            modelBuilder.Entity("projectSales.Server.Domain.Entities.Material", b =>
                {
                    b.HasOne("projectSales.Server.Domain.Entities.CategoriaMaterial", "Categoria")
                        .WithMany("Materiales")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_Materiales_Categoria");

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("projectSales.Server.Domain.Entities.ModuleAction", b =>
                {
                    b.HasOne("projectSales.Server.Domain.Entities.Module", "Module")
                        .WithMany("Actions")
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Actions_Modules");

                    b.Navigation("Module");
                });

            modelBuilder.Entity("projectSales.Server.Domain.Entities.PrecioTarifa", b =>
                {
                    b.HasOne("projectSales.Server.Domain.Entities.Marca", "Marca")
                        .WithMany("PreciosTarifas")
                        .HasForeignKey("MarcaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_PreciosTarifas_Marca");

                    b.HasOne("projectSales.Server.Domain.Entities.Material", "Material")
                        .WithMany("PreciosTarifas")
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_PreciosTarifas_Material");

                    b.HasOne("projectSales.Server.Domain.Entities.Proveedor", "Proveedor")
                        .WithMany("PreciosTarifas")
                        .HasForeignKey("ProveedorCifId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_PreciosTarifas_Proveedor");

                    b.Navigation("Marca");

                    b.Navigation("Material");

                    b.Navigation("Proveedor");
                });

            modelBuilder.Entity("projectSales.Server.Domain.Entities.ProveedorMarca", b =>
                {
                    b.HasOne("projectSales.Server.Domain.Entities.Marca", "Marca")
                        .WithMany("ProveedoresMarcas")
                        .HasForeignKey("MarcaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_ProvMarcas_Marca");

                    b.HasOne("projectSales.Server.Domain.Entities.Proveedor", "Proveedor")
                        .WithMany("ProveedoresMarcas")
                        .HasForeignKey("ProveedorCifId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_ProvMarcas_Prov");

                    b.Navigation("Marca");

                    b.Navigation("Proveedor");
                });

            modelBuilder.Entity("projectSales.Server.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("projectSales.Server.Domain.Entities.RefreshToken", "ReplacedByToken")
                        .WithMany("ReplacedTokens")
                        .HasForeignKey("ReplacedByTokenId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_RefreshTokens_ReplacedBy");

                    b.HasOne("projectSales.Server.Domain.Entities.RefreshToken", "RotatedFromToken")
                        .WithMany("RotatedTokens")
                        .HasForeignKey("RotatedFromTokenId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_RefreshTokens_RotatedFrom");

                    b.HasOne("projectSales.Server.Domain.Entities.UserSession", "Session")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_RefreshTokens_Session");

                    b.HasOne("projectSales.Server.Domain.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_RefreshTokens_User");

                    b.Navigation("ReplacedByToken");

                    b.Navigation("RotatedFromToken");

                    b.Navigation("Session");

                    b.Navigation("User");
                });

            modelBuilder.Entity("projectSales.Server.Domain.Entities.RolePermission", b =>
                {
                    b.HasOne("projectSales.Server.Domain.Entities.ModuleAction", "Action")
                        .WithMany("RolePermissions")
                        .HasForeignKey("ActionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_RolePermissions_Actions");

                    b.HasOne("projectSales.Server.Domain.Entities.Module", "Module")
                        .WithMany("RolePermissions")
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_RolePermissions_Modules");

                    b.HasOne("projectSales.Server.Domain.Entities.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_RolePermissions_Roles");

                    b.Navigation("Action");

                    b.Navigation("Module");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("projectSales.Server.Domain.Entities.UserRole", b =>
                {
                    b.HasOne("projectSales.Server.Domain.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_UserRoles_Roles");

                    b.HasOne("projectSales.Server.Domain.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_UserRoles_Users");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("projectSales.Server.Domain.Entities.UserSession", b =>
                {
                    b.HasOne("projectSales.Server.Domain.Entities.User", "User")
                        .WithMany("UserSessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_UserSessions_Users");

                    b.Navigation("User");
                });

            modelBuilder.Entity("projectSales.Server.Domain.Entities.CategoriaMaterial", b =>
                {
                    b.Navigation("Materiales");
                });

            modelBuilder.Entity("projectSales.Server.Domain.Entities.Marca", b =>
                {
                    b.Navigation("PreciosTarifas");

                    b.Navigation("ProveedoresMarcas");
                });

            modelBuilder.Entity("projectSales.Server.Domain.Entities.Material", b =>
                {
                    b.Navigation("PreciosTarifas");
                });

            modelBuilder.Entity("projectSales.Server.Domain.Entities.Module", b =>
                {
                    b.Navigation("Actions");

                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("projectSales.Server.Domain.Entities.ModuleAction", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("projectSales.Server.Domain.Entities.Proveedor", b =>
                {
                    b.Navigation("Contactos");

                    b.Navigation("PreciosTarifas");

                    b.Navigation("ProveedoresMarcas");
                });

            modelBuilder.Entity("projectSales.Server.Domain.Entities.RefreshToken", b =>
                {
                    b.Navigation("ReplacedTokens");

                    b.Navigation("RotatedTokens");
                });

            modelBuilder.Entity("projectSales.Server.Domain.Entities.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("projectSales.Server.Domain.Entities.User", b =>
                {
                    b.Navigation("RefreshTokens");

                    b.Navigation("UserRoles");

                    b.Navigation("UserSessions");
                });

            modelBuilder.Entity("projectSales.Server.Domain.Entities.UserSession", b =>
                {
                    b.Navigation("AccessTokenRevocations");

                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
